export const CITY_SUGGESTIONS = [
  "San Pedro Sula",
  "Tegucigalpa",
  "La Ceiba",
  "Choloma",
  "Puerto Cortés",
  "El Progreso",
  "Comayagua",
  "Siguatepeque",
  "Juticalpa",
  "Danlí",
  "Santa Rosa de Copán",
  "Tela",
  "Tocoa",
  "Villanueva",
  "Nacaome",
  "La Lima",
  "Catacamas",
  "Gracias",
  "Yoro",
  "Copán Ruinas",
] as const;
